### ISSUE TITLE
SSH Startups in ReadoutShell for 12.0-007 release are still not right:

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/NSCLDAQ#68]
If I start A readout, it seems to work but no tab shows up for that readout on the GUI.  If I click Begin when it's not ghosted
The tab shows up and I get the following in it along with an error message popup from Tcl saying the begin command took too long to execute.

I think there’s a stray ) that crept in somewhere.  Here’s what I get when I start and then begin:

```
11/15/2023 04:21:03 : output : SSHPipe@localhost:0: /usr/opt/nscldaq/12.0-007/bin/start.bash /global/home/users/rfoxkendo/testing/readout "/global/home/users/rfoxkendo/testing/readout/Readout "

11/15/2023 04:21:03 : output : SSHPipe@localhost:0: bash: -c: line 0: syntax error near unexpected token `)'

11/15/2023 04:21:03 : output : SSHPipe@localhost:0: bash: -c: line 0: `SING_IMAGE=/clusterfs/bgsdata/nscldaq/buster.img singularity shell --shell /bin/bash --bind /global/home/users/rfoxkendo/events,/usr/opt) /clusterfs/bgsdata/nscldaq/buster.img'

11/15/2023 04:21:03 : output : SSHPipe@localhost:0: Connection to localhost closed.

11/15/2023 04:21:03 : warning : SSHPipe@localhost:0: Source /global/home/users/rfoxkendo/testing/readout/Readout@localhost exited


```

Note the stray close parenthesis after /usr/opt in the --bind arguments for the singularity shell command.

Ron.

**Comment by aschester** [comment]
Removed extra ')' from set bindings $::env(APPTAINER_BIND)) in ssh.tcl

Fixed for 12.0-maint #69
Fixed for 12.1-dev #70

**Comment by aschester** [comment]
Merges fix the )) problem, but since APPTAINER_BIND does not contain the full source and destination information I'll leave this as open until this is resolved.

**Comment by aschester** [comment]
Merge #71 removes reading the bindings from environment variables completely, it only checks the ~/.singularity_bindpoints file. 
Merge #72 same for 12.1-dev

**Comment by rfoxkendo** [comment]
Can I get a binary tarball I can give them?

Ron

**Comment by aschester** [comment]
https://github.com/FRIBDAQ/NSCLDAQ/releases/tag/12.0-007 is up-to-date

**Comment by aschester** [comment]
I think this has been fixed?

**Comment by rfoxkendo** [comment]
Thers’s still a problem that I don’t know how to fix ..that has to do with the attempt to recover ~/stagarea if it’s a binding.   In that case, if the binding is not a -> a then the recovery fails.  E.g suppose I have a file system named  /junk and a directory named /junk/experiment that I want my stagearea to be in and I get really clever and do a binding :   /junk/experiment :/experiment and point my stagearea at ~/experiment

 

Last I checked that fails….unless I got it backwards and the user defined ~/stagarea -> /junk/experiment.

 

Of course out of the container stagarea is also a failure in that case.

 

The work around is to bind /junk:/junk and point ~/stagearea -> /junk/experiment

 

So it’s not a show stopper.

 

 

RF.
